version: '3'

services:
  db:
    image: postgres
    container_name: ms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ms_data:/var/lib/postgresql
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  ms_data: