server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ms-user
    username: postgres
    password: admin

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      group-id: spring-ms

  jpa:
    hibernate:
      ddl-auto: update

topic:
  name:
    producer: topic_spring_ms

auto:
  create:
    topics:
      enable: true