server:
  port: 8082

spring:
  application:
    name: email-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    username: postgres
    password: admin

  kafka:
    bootstrap-servers: localhost:29092

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: your-host
    port: your-post
    username: your-username
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    smtp:
      ssl:
        protocols: TLSv1.2

topic:
  name:
    producer: topic_spring_ms